import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import './styles.css';
import './additions.css';
import './documents.css';
import './brand.css';
import './game.css';
import './mystic.css';
import './warmth.css';
import './map-interactions.css';
import './profile.css';
import './task-views.css';
import './preferences.css';
import './light-theme.css';
import './categories.css';
import './welcome-bubbles.css';
import './language.css';
import './social.css';
createRoot(document.getElementById('root')).render(<App />);
