import {t,locale} from './i18n.js';
import {circleMembers,rankMembers,messageText} from './social-model.js';
export function createSocial({root,getState,persist,render,navigate,icon,esc,signal,human}) {
  let draft='';
  const members=()=>circleMembers(getState());
  function face(m) {return `<span class="rs-face ${m.avatar.gender==='male'?'is-male':'is-female'}" aria-hidden="true">${human({person:m.avatar,energy:100,mini:true})}</span>`;}
  function view() {
    const race=getState().view==='race',team=members();
    return `<section class="rs-social"><header class="rs-header"><div><span class="rs-eyebrow">YOUR CIRCLE</span><h1>${t('Tvoja ekipa','Your circle')}<span class="rs-count">${team.length}</span></h1></div><button type="button" data-social-map aria-label="${t('Otvori ekipnu mapu','Open group map')}">${icon('route')}</button></header><nav class="rs-tabs" aria-label="${t('Ekipni prikazi','Circle views')}"><button type="button" data-view="groupchat" aria-current="${!race?'page':'false'}">${icon('users')}Group chat</button><button type="button" data-view="race" aria-current="${race?'page':'false'}">${icon('trophy')}Weekly relAI Race</button></nav><p class="rs-preview">${t('Primjer ekipe · lokalni UX pregled','Sample circle · local UX preview')}</p>${race?raceView():chatView(team)}</section>`;
  }
  function raceView() {
    const ranked=rankMembers(members()),podium=[ranked[1],ranked[0],ranked[2]];
    return `<div class="rs-race"><div class="rs-race-title"><span>${t('OVAJ TJEDAN','THIS WEEK')}</span><h2>Small steps.<br><em>Big energy.</em></h2></div><div class="rs-podium" aria-label="${t('Tjedno postolje','Weekly podium')}">${podium.map((m,i)=>`<div class="rs-place rs-place-${i===1?'winner':i===0?'second':'third'}"><span class="rs-crown">${i===1?icon('trophy'):''}</span><div class="rs-podium-avatar">${human({person:m.avatar,energy:m.hp,mini:true})}</div><strong class="rs-name">${esc(m.name)}${m.self?` <small>(${t('ti','you')})</small>`:''}</strong><span class="rs-score">${m.xp} XP</span><div class="rs-plinth"><b>${m.rank}</b><span>${m.steps} ${t('koraka','steps')}</span></div></div>`).join('')}</div><ol class="rs-ranking" aria-label="${t('Tjedni poredak','Weekly standings')}">${ranked.map(m=>`<li class="${m.self?'is-self':''}"><span class="rs-rank">${m.rank}</span>${face(m)}<div><strong>${esc(m.name)}${m.self?` <small>(${t('ti','you')})</small>`:''}</strong><span>${m.steps} ${t('dovršenih zadataka','completed tasks')}</span></div><b>${m.xp}<small> XP</small></b></li>`).join('')}</ol><p class="rs-rules">${t('Poredak po koracima, zatim XP-u. Novi tjedan, nova prilika.','Ranked by steps, then XP. New week, new chance.')}</p><button type="button" class="rs-map-link" data-social-map>${icon('route')}${t('Vidi ekipu na mapi','See your circle on the map')}${icon('arrow-right')}</button></div>`;
  }
  function chatView(team) {
    const seed=[{id:'s1',author:'luna',text:t('Šest malih koraka ovaj tjedan. Idemo dalje ✨','Six little steps this week. Let’s keep going ✨'),time:'09:41'},{id:'s2',author:'ivan',text:t('Stižem te! Još jedan task i slobodno popodne 🙌','Catching up! One more task, then a free afternoon 🙌'),time:'09:43'},{id:'s3',author:'mia',text:t('Mali pomaci se računaju 💙','Small steps count 💙'),time:'09:45'}];
    const messages=[...seed,...(getState().circleMessages||[])];
    return `<div class="rs-members">${team.map(m=>`<div>${face(m)}<span>${esc(m.name)}</span></div>`).join('')}</div><div class="rs-chat-log" role="log" aria-label="${t('Poruke ekipe','Circle messages')}" aria-live="polite">${messages.map(msg=>{const m=team.find(p=>p.id===msg.author)||team[3];return `<article class="rs-message ${m.self?'is-own':''}">${m.self?'':face(m)}<div><span class="rs-message-author">${esc(m.name)}</span><p>${esc(msg.text)}</p><time>${esc(msg.time)}</time></div></article>`;}).join('')}</div><form class="rs-composer" id="rs-message-form"><label class="rg-sr-only" for="rs-message">${t('Poruka ekipi','Message your circle')}</label><input id="rs-message" name="message" maxlength="1000" autocomplete="off" placeholder="${t('Pošalji malo dobre energije…','Send a little good energy…')}" value="${esc(draft)}"><button type="submit" aria-label="${t('Pošalji poruku','Send message')}" ${messageText(draft)?'':'disabled'}>${icon('arrow-right')}</button><small>${t('Poruke ostaju samo na ovom uređaju.','Messages stay on this device only.')}</small></form>`;
  }
  root.addEventListener('input',e=>{if(e.target.id==='rs-message'){draft=e.target.value;root.querySelector('.rs-composer button').disabled=!messageText(draft);}},{signal});
  root.addEventListener('submit',e=>{if(e.target.id!=='rs-message-form')return;e.preventDefault();const text=messageText(draft);if(!text)return;const state=getState();state.circleMessages=[...(state.circleMessages||[]),{id:crypto.randomUUID(),author:'self',text,time:new Date().toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'}),createdAt:new Date().toISOString()}];draft='';persist();render();const input=root.querySelector('#rs-message');input?.focus();input?.scrollIntoView({block:'nearest'});},{signal});
  root.addEventListener('click',e=>{if(e.target.closest('[data-social-map]')){getState().mode='group';getState().prefs.showTeam=true;navigate('map');}},{signal});
  return {view};
}
